//==========================================================================================
//==========================================================================================
//===============================ppool_data_display_script.js===============================
// This script contains the functions responsible for displaying the data retrieved from the
// server related to a specific PPool in the PPool dashboard page, as well as functions
// responsible for handling the events triggered by user interactions in that page.=========
//==========================================================================================
//==========================================================================================

//=========================================================================================
//====================================Import statements====================================
//=========================================================================================

import * as genericScript from "../../scripting.js"
import * as mainScript from "../data_handling_main_script.js"
import * as dataRetrievalScript from "../data_retrieval_script.js"
import * as pgridDataDisplayScript from  "../PGRID/pgrid_data_display_script.js"
import * as pnodeDataDisplayScript from  "../PNODE/pnode_data_display_script.js"
import * as ppoolDataEditScript from "./ppool_data_edit_script.js"
import * as pnodeDataEditScript from "../PNODE/pnode_data_edit_script.js"
import * as editorComponents from "../editor_components.js"
import * as typeDefinitions from "../../types.js"

//=========================================================================================
//=========================================================================================
//=========================================================================================

//#region PPOOLS

//=========================================================================================
/**
 * This function retrieves the dashboard data for a specific PPool from the server and displays it in the PPool dashboard page, including setting up the event listeners for the interactive elements in that page.
 * @param {String} pgridID The ID of the PGrid to which the PPool belongs.
 * @param {String} ppoolID The ID of the PPool for which to retrieve and display the dashboard data.
 * @param {Object} e The event object generated by the user interaction that triggered the display of the PPool dashboard (e.g. clicking on the PPool name in the navigation tree), which can be used to position the dashboard page accordingly in relation to the clicked element.
 */
//=========================================================================================
export async function displayPPoolDashboardData(pgridID : Number, ppoolID : Number, e : Event | null)
{
    let dashboardData : typeDefinitions.PPoolDashboardData = await dataRetrievalScript.getPPoolDashboardData(pgridID, ppoolID) as typeDefinitions.PPoolDashboardData;
    await genericScript.switchCustomSection('ppool_mgmt.html', 'content', 'content');
    document.getElementById('content')!.scrollTop = 0;

    document.getElementById("createPNodeButton")?.addEventListener("click", () => {
        createNewPNode(dashboardData, e);
    });

    const centeredSettingsModalBoxContent = `<div>
        <h2>General</h2>
        <div class="centeredSettingsModalBoxSectionContent">
            <div class="centeredSettingsModalBoxSectionItem">
                <h3>PPool Name:</h3>
                <input type="text" value="${dashboardData.ppoolFullInfo.ppool_name}" spellcheck="false" />
            </div>
            <div class="centeredSettingsModalBoxSectionItem">
                <h3 style="height: 100px;">PPool Readme Text:</h3>
                <textarea spellcheck="false">${dashboardData.ppoolFullInfo.ppool_readme_text}</textarea>
            </div>
        </div>
    </div>
    
    <div style="margin-top: 300px;">
        <h2 style="color: var(--accent);">Danger Zone</h2>
        <div class="centeredSettingsModalBoxSectionContent">
            <div class="centeredSettingsModalBoxSectionItem" style="width: 20%;">
                <button id="ppoolDeleteBTN">DELETE PPOOL</button>
            </div>
        </div>
    </div>`;

    document.getElementById("editPPoolSettingsBTN")!.addEventListener("click", () => {
        const PPoolSettingsModalBox = new editorComponents.centeredSettingsModalBox("Edit PPool Settings", centeredSettingsModalBoxContent, () => {});

        document.getElementById("ppoolDeleteBTN")!.addEventListener("click", async (event : Event) => {
            console.log(dashboardData.ppoolFullInfo.ppool_id);
            await ppoolDataEditScript.DeletePPool(dashboardData.ppoolFullInfo.ppool_id);
            PPoolSettingsModalBox.hideSettingsBox();
            await pgridDataDisplayScript.displayPGridDashboardData(pgridID, event, true);
        });
    });

    displayPPoolMainInfo(dashboardData, pgridID, e);
    genericScript.resetElementEventListeners('_singleOperationBTN');

    //Assign Event Listeners to single/batch Operations View Switch Buttons
    document.getElementById('_singleOperationBTN')!.addEventListener('click', () => {
        toggleSingleNBatchOperationsTableView('_singleOperationBTN')
    });
    document.getElementById('_batchOperationBTN')!.addEventListener('click', () => {
        toggleSingleNBatchOperationsTableView('_batchOperationBTN')
    });

    //Make the current PNode the active node in the navigation tree
    mainScript.updateActiveTreeNode(dashboardData.ppoolFullInfo.ppool_name);

    document.getElementById("_hardware_link")!.classList.add('active');
    document.getElementById("_backToGridBTN")!.addEventListener("click", async () => {
        await pgridDataDisplayScript.displayPGridDashboardData(pgridID, e, false);
    });

    document.getElementById("changePPoolReadmeBTN")!.addEventListener("click", () => {
        const changesSaveOperation = (e : Event, selfInstance : editorComponents.sideConfigurationEditWizzard) => {
            const newReadmeTXT = (document.getElementById('readmeTextTextArea') as HTMLTextAreaElement)!.value;
            ppoolDataEditScript.PPoolUpdateReadmeText(ppoolID, pgridID, newReadmeTXT);
        };

        const readmeTextEditorBox = new editorComponents.sideConfigurationEditWizzard('Edit Readme Text', changesSaveOperation);
        readmeTextEditorBox.insertTextArea('readmeTextTextArea', 'Readme Text', 'Write Readme Text', dashboardData.ppoolFullInfo.ppool_readme_text, null);
    });

    displayPPoolsPnodesListInfo(dashboardData);
    displayPPoolPNodesLoginAudits(dashboardData);
    displayPPoolAttentionLEDMarkedPNodes(dashboardData);
    displayPPoolErrorLogsInfo(dashboardData);
    displayPPoolOperationHistory(dashboardData);
}

//=========================================================================================
/**
 * Displays the main information for a PPool in the dashboard.
 * @param {Object} dashboardData The data containing the PPool information to display.
 * @param {String} _pgridID The ID of the PGrid to which the PPool belongs.
 * @param {Object} e The event object generated by the user interaction.
 */
//=========================================================================================
function displayPPoolMainInfo(dashboardData : typeDefinitions.PPoolDashboardData, _pgridID : Number, e : Event | null)
{
    document.getElementById("_ppoolName")!.innerText = dashboardData.ppoolFullInfo.ppool_name;
    document.getElementById("_propsPPoolName")!.innerText = dashboardData.ppoolFullInfo.ppool_name;
    document.getElementById("_propsPPoolID")!.innerText = dashboardData.ppoolFullInfo.ppool_id.toString();
    document.getElementById("_propsPPoolParentPGridName")!.innerText = dashboardData.ppoolFullInfo.ppool_parent_pgrid_name;
    document.getElementById("_propsPPoolCreationDatetime")!.innerText = dashboardData.ppoolFullInfo.ppool_creation_datetime;
    document.getElementById("_propsPPoolLastUpdateDatetime")!.innerText = dashboardData.ppoolFullInfo.ppool_last_update_datetime;
    document.getElementById("_propsPPoolTag")!.innerText = dashboardData.ppoolFullInfo.ppool_tag;
    document.getElementById("_propsPPoolPNodesCount")!.innerText = dashboardData.ppoolFullInfo.ppool_pnodes_count.toString();
    document.getElementById("_propsPPoolActivePNodesCount")!.innerText = dashboardData.ppoolFullInfo.ppool_active_pnodes_count.toString();
    document.getElementById("_ppoolReadmeTextParagraph")!.innerText = dashboardData.ppoolFullInfo.ppool_readme_text;
    document.getElementById("reloadSettingsBTN")!.addEventListener("click", async () => {
        await displayPPoolDashboardData(_pgridID, dashboardData.ppoolFullInfo.ppool_id, e);
    });
}

//=========================================================================================
/**
 * Displays the list of PNodes associated with a PPool in the dashboard.
 * @param {Object} dashboardData The data containing the PPool and its associated PNodes.
 */
//=========================================================================================
function displayPPoolsPnodesListInfo(dashboardData : typeDefinitions.PPoolDashboardData)
{
    for(let i = 0; i < dashboardData.ppoolPNodesFullList.length; i++){
        document.getElementById("pnodesNoDeviceSelectedWarning")!.style = "display: none;";
        const gridTile = `<div class="tile" id="PNode-${i}">
                                <div class="tile-header">
                                    <img class="tile-icon" style="width: 50%;" src="fontawesome-free-7.0.0-web\\fontawesome-free-7.0.0-web\\svgs\\solid\\server.svg" />
                                    <h3>${dashboardData.ppoolPNodesFullList[i]!.pnodeName}</h3>
                                </div>
                                <div class="tile-props">
                                    <p><strong>Logical Partitions:</strong> ${dashboardData.ppoolPNodesFullList[i]!.pnodeLparsCount}</p>
                                </div>
                            </div>`
        document.getElementById("_ppoolPNodesTiledList")!.innerHTML += gridTile;

        requestAnimationFrame((e) => {
            document.getElementById(`PNode-${i}`)!.addEventListener('click', (e) => {
                pnodeDataDisplayScript.displayPNodesDashboardData(dashboardData.ppoolPNodesFullList[i]!.pnodeID, dashboardData.ppoolFullInfo.ppool_id, 1);
            });
        });
    }
}

//=========================================================================================
/**
 * Displays the login audits for the PNodes associated with a PPool in the dashboard.
 * @param {Object} dashboardData The data containing the PPool and its associated PNode login audits.
 */
//=========================================================================================
function displayPPoolPNodesLoginAudits(dashboardData : typeDefinitions.PPoolDashboardData)
{
    document.getElementById("_ppoolPnodesLoginAuditsCount")!.innerText = dashboardData.ppoolLoginAudits.length.toString();
    for(let i = 0; i < dashboardData.ppoolLoginAudits.length; i++){
        const tableRow = `
        <tr>
            <td>LOG-${dashboardData.ppoolLoginAudits[i]!.login_audit_id}</td>
            <td>${dashboardData.ppoolLoginAudits[i]!.login_audit_pnode_nickname}</td>
            <td>${dashboardData.ppoolLoginAudits[i]!.login_audit_fsp_user}</td>
            <td>${dashboardData.ppoolLoginAudits[i]!.login_audit_datetime}</td>
            <td><span class="state-pill" style="background:rgba(34,197,94,0.08);color:var(--success)">${dashboardData.ppoolLoginAudits[i]!.login_audit_login_status}</span></td>
            <td>${dashboardData.ppoolLoginAudits[i]!.login_audit_location}</td>
        </tr>`

        document.getElementById("_ppoolLoginAuditsLogs")!.innerHTML += tableRow;
    }
}

//=========================================================================================
/**
 * Displays the list of PNodes with attention LEDs marked in the dashboard.
 * @param {Object} dashboardData The data containing the PPool and its associated PNodes with attention LEDs marked.
 */
//=========================================================================================
function displayPPoolAttentionLEDMarkedPNodes(dashboardData : typeDefinitions.PPoolDashboardData)
{
    document.getElementById("_ppoolAttentionLedSignedNodesCount")!.innerText = dashboardData.ppoolAttentionLEDMarkedPNodes.length.toString();
    for(let i = 0; i < dashboardData.ppoolAttentionLEDMarkedPNodes.length; i++){
        const tableRow = `
        <tr>
            <td>
                <span class="state-pill" style="background:rgba(255,206,84,0.06);color:#ffd166">
                    LOG-${dashboardData.ppoolAttentionLEDMarkedPNodes[i]!.pnode_nickname}
                </span>
            </td>
        </tr>`;

        document.getElementById("_ppoolAttentionLedSignedNodesList")!.innerHTML += tableRow;
    }
}

//=========================================================================================
/**
 * Displays the error logs for the PNodes associated with a PPool in the dashboard.
 * @param {Object} dashboardData The data containing the PPool and its associated PNode error logs.
 */
//=========================================================================================
function displayPPoolErrorLogsInfo(dashboardData : typeDefinitions.PPoolDashboardData)
{
    document.getElementById("_ppoolPnodesErrorLogsOverviewCount")!.innerText = dashboardData.ppoolErrorLogs.length.toString();

    for(let i = 0; i < dashboardData.ppoolErrorLogs.length; i++)
    {
        let ActionFlags = "";
        for(let j = 0; j < dashboardData.ppoolErrorLogs[i]!.actionFlags.length; j++)
        {
            ActionFlags += j == 0 ? `${dashboardData.ppoolErrorLogs[i]!.actionFlags[j]}` : `, ${dashboardData.ppoolErrorLogs[i]!.actionFlags[j]}`
        }

        const tableRow = `
        <tr>
            <td>${dashboardData.ppoolErrorLogs[i]!.errorLogID}</td>
            <td>${dashboardData.ppoolErrorLogs[i]!.pNodeNickname}</td>
            <td>${dashboardData.ppoolErrorLogs[i]!.pPoolName}</td>
            <td>${dashboardData.ppoolErrorLogs[i]!.logDate} ${dashboardData.ppoolErrorLogs[i]!.logTime}</td>
            <td>${dashboardData.ppoolErrorLogs[i]!.driverName}</td>
            <td>${dashboardData.ppoolErrorLogs[i]!.subsystem}</td>
            <td><span class="state-pill" style="background:rgba(255,159,67,0.06);color:#ff9f43">${dashboardData.ppoolErrorLogs[i]!.eventSeverity}</span></td>
            <td>${ActionFlags}</td>
            <td>${dashboardData.ppoolErrorLogs[i]!.actionStatus}</td>
            <td>${dashboardData.ppoolErrorLogs[i]!.referenceCode}</td>
        </tr>`;

        document.getElementById("_ppoolErrorLogs")!.innerHTML += tableRow;
    }
}

//=========================================================================================
/**
 * Displays the single operation history for the PNodes associated with a PPool in the dashboard.
 * @param {Object} dashboardData The data containing the PPool and its associated PNode single operation history.
 */
//=========================================================================================
function displayPPoolPNodesSingleOperationHistory(dashboardData : typeDefinitions.PPoolDashboardData)
{
    let ppoolOperationLogsData = dashboardData.ppoolOperationLogs;

    document.getElementById("_ppoolPNodesSingleOperationLogsCount")!.innerText = ppoolOperationLogsData.pnodesSingleOperationHistory.length.toString();
    for(let i = 0; i< ppoolOperationLogsData.pnodesSingleOperationHistory.length; i++){
        let completionStatusBadgeBKG = ppoolOperationLogsData.pnodesSingleOperationHistory[i]!.operationCompletionStatus == "SUCCESS" ? "rgba(34,197,94,0.08)" : "rgba(255,159,67,0.06)";
        let completionStatusBadgeTextColor = ppoolOperationLogsData.pnodesSingleOperationHistory[i]!.operationCompletionStatus == "SUCCESS" ? "var(--success)" : "#ff9f43";
        
        document.getElementById("_ppoolPNodesSingleOperationLogs")!.innerHTML += `<tr>
            <td>${ppoolOperationLogsData.pnodesSingleOperationHistory[i]!.operationID}</td>
            <td>${ppoolOperationLogsData.pnodesSingleOperationHistory[i]!.operationCatName}</td>
            <td>${ppoolOperationLogsData.pnodesSingleOperationHistory[i]!.operationSourcePNodeName}</td>
            <td>${ppoolOperationLogsData.pnodesSingleOperationHistory[i]!.operationBatchOperationName}</td>
            <td>${ppoolOperationLogsData.pnodesSingleOperationHistory[i]!.operationAction}</td>
            <td><span class="state-pill" style="background:${completionStatusBadgeBKG};color:${completionStatusBadgeTextColor}">${ppoolOperationLogsData.pnodesSingleOperationHistory[i]!.operationCompletionStatus}</span></td>
            <td>${ppoolOperationLogsData.pnodesSingleOperationHistory[i]!.operationDateTime}</td>
            <td>${ppoolOperationLogsData.pnodesSingleOperationHistory[i]!.operationSourceUserName}</td>
        </tr>`;
    }
}

//=========================================================================================
/**
 * Displays the batch operation history for the PNodes associated with a PPool in the dashboard.
 * @param {Object} dashboardData The data containing the PPool and its associated PNode batch operation history.
 */
//=========================================================================================
function displayPPoolBatchOperationHistory(dashboardData : typeDefinitions.PPoolDashboardData)
{
    let ppoolOperationLogsData = dashboardData.ppoolOperationLogs;
    
    document.getElementById("_ppoolBatchOperationLogsCount")!.innerText = ppoolOperationLogsData.ppoolsBatchOperationHistory.length.toString();
    for(let i = 0; i< ppoolOperationLogsData.ppoolsBatchOperationHistory.length; i++){
        document.getElementById("_ppoolBatchOperationLogs")!.innerHTML += `<tr>
            <td>${ppoolOperationLogsData.ppoolsBatchOperationHistory[i]!.batchOperationID}</td>
            <td>${ppoolOperationLogsData.ppoolsBatchOperationHistory[i]!.batchOperationCatName}</td>
            <td>${ppoolOperationLogsData.ppoolsBatchOperationHistory[i]!.batchOperationSourcePPoolName}</td>
            <td>${ppoolOperationLogsData.ppoolsBatchOperationHistory[i]!.batchOperationAction}</td>
            <td>${ppoolOperationLogsData.ppoolsBatchOperationHistory[i]!.batchOperationDateTime}</td>
            <td>${ppoolOperationLogsData.ppoolsBatchOperationHistory[i]!.batchOperationSourceUserName}</td>
        </tr>`;
    }
}

//=========================================================================================
/**
 * Displays the operation history for the PNodes associated with a PPool in the dashboard.
 * @param {Object} dashboardData The data containing the PPool and its associated PNode operation history.
 */
//=========================================================================================
function displayPPoolOperationHistory(dashboardData : typeDefinitions.PPoolDashboardData)
{
    displayPPoolPNodesSingleOperationHistory(dashboardData);
    displayPPoolBatchOperationHistory(dashboardData);
}

//=========================================================================================
/**
 * Toggles the view between single and batch operations tables in the dashboard.
 * @param {String} _clickedBTNID The ID of the clicked button.
 */
//=========================================================================================
function toggleSingleNBatchOperationsTableView(_clickedBTNID : string)
{
    switch(_clickedBTNID){
        case '_singleOperationBTN':
            document.getElementById("ppoolPNodesSingleOperationHistory")!.style.display = 'block';
            document.getElementById("ppoolBatchOperationHistory")!.style.display = 'none';
            break;
        case '_batchOperationBTN':
            document.getElementById("ppoolBatchOperationHistory")!.style.display = 'block';
            document.getElementById("ppoolPNodesSingleOperationHistory")!.style.display = 'none';
            break;
    }
    
    genericScript.toggle2SideBTN(['_singleOperationBTN', '_batchOperationBTN'], _clickedBTNID);
}

function createNewPNode(dashboardData : typeDefinitions.PPoolDashboardData, event : Event | null) {
    const ppoolCreationWizzardSubmitAction = null;
    const ppoolCreationWizzard = new editorComponents.sideConfigurationEditWizzard("PNode Creation Wizzard", ppoolCreationWizzardSubmitAction);

    const pnodeSyncMachineDataBTNAction = new typeDefinitions.FunctionObject(async (args : Array<any>) => {
        const pnodeData : typeDefinitions.MachineConnectionCredentialsData = {
            COMPort: (document.getElementById("pnodeCOMPortField") as HTMLInputElement)!.value,
            username: (document.getElementById("pnodeASMIUsernameField") as HTMLInputElement)!.value,
            password: (document.getElementById("pnodeASMIPasswordField") as HTMLInputElement)!.value
        };

        if(pnodeData.COMPort == "" || pnodeData.username == "" || pnodeData.password == "") {
            editorComponents.showErrorMessage("Connection property fields aren't fully filled in.");
            return;
        }

        genericScript.showScreenLoadingPane();
        let NewMachineSyncInfo : typeDefinitions.MachineConnectionResponseData = await pnodeDataEditScript.syncNewPNodeMachine(pnodeData) as typeDefinitions.MachineConnectionResponseData;
        
        console.log(NewMachineSyncInfo);

        document.getElementById("pnodeSynchronizeMachineDataBTN")!.style.borderColor = "var(--success)";
        document.getElementById("pnodeSynchronizeMachineDataBTN")!.style.color = "var(--success)";

        console.log(NewMachineSyncInfo);
        console.log(NewMachineSyncInfo.systemInfo);
        console.log(NewMachineSyncInfo.systemInfo.serialNumber);

        const newPNodeInfo : typeDefinitions.NewPNodeData = {
            pnodeBasicInfo: {
                pNodeID: 200,
                nickName: (document.getElementById("pnodeNameField") as HTMLInputElement)!.value,
                parentPPoolID: dashboardData.ppoolFullInfo.ppool_id,
                readmeText: (document.getElementById("pnodeReadmeTextField") as HTMLInputElement)!.value,
                serialCOMPort: pnodeData.COMPort,
                systemMachineSerialNumber: NewMachineSyncInfo.systemInfo.serialNumber,
                systemMachineTypeModel: NewMachineSyncInfo.systemInfo.machineTypeModel,
                systemModelName: NewMachineSyncInfo.systemInfo.systemName,
                systemPSeries: (document.getElementById("pnodePSeriesField") as HTMLInputElement)!.value
            },
            pnodeFSPInfo: {
                fspasmiUsername: pnodeData.username,
                fspasmiPasswordHash: pnodeData.password,
                fspasmiVersion: NewMachineSyncInfo.systemInfo.asmiVersion,
                fspid: 200,
                fspasmiLocalTime: ""
            },
            pnodeOSUserInfoType: {
                osid: 200,
                osipAddress: (document.getElementById("pnodeOSIPAddressField") as HTMLInputElement)!.value,
                osUsername: (document.getElementById("pnodeOSUsernameField") as HTMLInputElement)!.value,
                osPasswordHash: (document.getElementById("pnodeOSPasswordField") as HTMLInputElement)!.value,
                osFamily: (document.getElementById("pnodeOSFamilyDropDownBTN") as HTMLButtonElement)!.value,
            }
        }

        console.log(newPNodeInfo);

        const newPPoolCreationWizzardSubmitAction = async (e : Event, selfInstance : editorComponents.sideConfigurationEditWizzard) => {
            const newPNodeInfo : typeDefinitions.NewPNodeData = {
                pnodeBasicInfo: {
                    pNodeID: 200,
                    nickName: (document.getElementById("pnodeNameField") as HTMLInputElement)!.value,
                    parentPPoolID: dashboardData.ppoolFullInfo.ppool_id,
                    readmeText: (document.getElementById("pnodeReadmeTextField") as HTMLInputElement)!.value,
                    serialCOMPort: pnodeData.COMPort,
                    systemMachineSerialNumber: NewMachineSyncInfo.systemInfo.serialNumber,
                    systemMachineTypeModel: NewMachineSyncInfo.systemInfo.machineTypeModel,
                    systemModelName: NewMachineSyncInfo.systemInfo.systemName,
                    systemPSeries: (document.getElementById("pnodePSeriesField") as HTMLInputElement)!.value
                },
                pnodeFSPInfo: {
                    fspasmiUsername: pnodeData.username,
                    fspasmiPasswordHash: pnodeData.password,
                    fspasmiVersion: NewMachineSyncInfo.systemInfo.asmiVersion,
                    fspid: 200,
                    fspasmiLocalTime: ""
                },
                pnodeOSUserInfoType: {
                    osid: 200,
                    osipAddress: (document.getElementById("pnodeOSIPAddressField") as HTMLInputElement)!.value,
                    osUsername: (document.getElementById("pnodeOSUsernameField") as HTMLInputElement)!.value,
                    osPasswordHash: (document.getElementById("pnodeOSPasswordField") as HTMLInputElement)!.value,
                    osFamily: (document.getElementById("pnodeOSFamilyDropDownBTN") as HTMLButtonElement)!.value,
                }
            }

            await pnodeDataEditScript.CreateNewPNode(newPNodeInfo);
            
            displayPPoolDashboardData(dashboardData.ppoolFullInfo.ppool_parent_pgrid_id, dashboardData.ppoolFullInfo.ppool_id, event);
        };

        ppoolCreationWizzard.resetSubmitButtonClickELAction(newPPoolCreationWizzardSubmitAction);
    }, []);

    ppoolCreationWizzard.insertInputField("pnodeNameField", "PNode Nickname", "Sample PNode", "");
    ppoolCreationWizzard.insertTextArea("pnodeReadmeTextField", "PNode Readme Text", "Sample PNode Readme", "", "200px");
    ppoolCreationWizzard.insertInputField("pnodePSeriesField", "PNode PSeries", "POWER5", "");
    ppoolCreationWizzard.insertInputField("pnodeCOMPortField", "PNode COM port", "COM1", "");
    ppoolCreationWizzard.insertInputField("pnodeASMIUsernameField", "PNode ASMI Username", "admin", "");
    ppoolCreationWizzard.insertInputField("pnodeASMIPasswordField", "PNode ASMI Password", "..........", "", true);
    ppoolCreationWizzard.insertButton("pnodeSynchronizeMachineDataBTN", "Test connection", pnodeSyncMachineDataBTNAction);
    ppoolCreationWizzard.insertDropdownField("pnodeOSFamilyDropDownBTN", "pnodeOSFamilyDropDown", "PNode Main OS Family", ["AIX", "LINUX"], "AIX");
    ppoolCreationWizzard.insertInputField("pnodeOSUsernameField", "PNode Main OS Username", "root", "");
    ppoolCreationWizzard.insertInputField("pnodeOSPasswordField", "PNode Main OS Password", "..........", "", true);
    ppoolCreationWizzard.insertInputField("pnodeOSIPAddressField", "PNode Main OS IP Address", "192.168.0.200", "");
}

//#endregion PPOOLS